# Chat ExaOne 프로젝트 설정
name: chat-exa-one
version: 0.1.0
private: true

scripts:
  # YAML 변환
  yaml: node yaml-to-json.mjs
  
  # 개발 관련 스크립트
  dev:tsc: tsc -p server.tsconfig.json --watch
  dev:server: cross-env NODE_OPTIONS= nodemon --watch src-server --exec "node .server/server.js"
  dev: npm run build-server && concurrently "npm run dev:tsc" "npm run dev:server"
  
  # 디버그
  predebug: cross-env NODE_OPTIONS= npm run yaml
  debug:server: cross-env NODE_OPTIONS='--inspect=9229' nodemon --watch src-server --exec "node .server/server.js"
  debug: cross-env NODE_OPTIONS= concurrently "npm run dev:tsc" "npm run debug:server"

  # 빌드 관련 스크립트
  build-server: tsc -p server.tsconfig.json
  build-next: next build
  build: npm run build-server && npm run build-next

  # 배포 관련 스크립트
  dist: >-
    rimraf .server .next dist &&
    npm run build && 
    copyfiles -u 1 ".server/**/*" dist/server/ && 
    copyfiles -u 1 ".next/**/*" dist/.next/ && 
    copyfiles package.json dist/
  
  # 서버 실행
  start: >-
    cd dist && 
    npm install --omit=dev && 
    cross-env NODE_ENV=production node server/server.js
  
  # 기타
  lint: npm run yaml && next lint

# 프로덕션 의존성
dependencies:
  next: 15.1.7
  react: ^19.0.0
  react-dom: ^19.0.0
  react-hot-toast: ^2.5.2
  socket.io: ^4.8.1

# 개발 의존성
devDependencies:
  "@eslint/eslintrc": ^3
  "@types/node": ^20.17.19
  "@types/react": ^19
  "@types/react-dom": ^19
  concurrently: ^9.1.2
  copyfiles: ^2.4.1
  cross-env: ^7.0.3
  eslint: ^9
  eslint-config-next: 15.1.7
  js-yaml: ^4.1.0
  nodemon: ^3.1.9
  postcss: ^8
  prettier: ^3.5.1
  rimraf: ^6.0.1
  socket.io-client: ^4.8.1
  tailwindcss: ^3.4.1
  ts-node: ^10.9.2
  typescript: ^5.7.3 